import Foundation
import os

// Exports captured HTTP transactions as an inferred OpenAPI 3.0.3 contract.

// MARK: - OpenAPIExportFormat

enum OpenAPIExportFormat {
    case json
    case yaml
    case html
}

// MARK: - OpenAPIExportOptions

struct OpenAPIExportOptions {
    var format: OpenAPIExportFormat = .yaml
    var title: String = "Rockxy Captured API"
    var version: String = "1.0.0"
    var includeExamples: Bool = false
}

// MARK: - OpenAPIExportResult

struct OpenAPIExportResult {
    let data: Data
    let document: [String: Any]
    let exportedTransactionCount: Int
    let skippedTransactionCount: Int
}

// MARK: - OpenAPIExporter

struct OpenAPIExporter: ExporterPlugin {
    // MARK: Internal

    let name = "OpenAPI Exporter"
    let fileExtension = "yaml"

    func export(transactions: [HTTPTransaction]) throws -> Data {
        try export(
            transactions: transactions,
            options: OpenAPIExportOptions(format: .yaml)
        ).data
    }

    func export(
        transactions: [HTTPTransaction],
        options: OpenAPIExportOptions
    ) throws -> OpenAPIExportResult {
        let builder = OpenAPIDocumentBuilder(options: options)
        let buildResult = builder.build(from: transactions)
        let document = buildResult.document

        let data: Data = switch options.format {
        case .json:
            try JSONSerialization.data(withJSONObject: document, options: [.prettyPrinted, .sortedKeys])
        case .yaml:
            Data(OpenAPIYAMLWriter().string(from: document).utf8)
        case .html:
            try OpenAPIHTMLRenderer().data(for: document)
        }

        Self.logger.info(
            "Exported \(buildResult.exportedTransactionCount) transactions to OpenAPI; skipped \(buildResult.skippedTransactionCount)"
        )
        return OpenAPIExportResult(
            data: data,
            document: document,
            exportedTransactionCount: buildResult.exportedTransactionCount,
            skippedTransactionCount: buildResult.skippedTransactionCount
        )
    }

    static func isEligible(_ transaction: HTTPTransaction) -> Bool {
        OpenAPITransactionFilter.isEligible(transaction)
    }

    // MARK: Private

    private static let logger = Logger(
        subsystem: RockxyIdentity.current.logSubsystem,
        category: "OpenAPIExporter"
    )
}

// MARK: - OpenAPIDocumentBuildResult

private struct OpenAPIDocumentBuildResult {
    let document: [String: Any]
    let exportedTransactionCount: Int
    let skippedTransactionCount: Int
}

// MARK: - OpenAPIDocumentBuilder

private struct OpenAPIDocumentBuilder {
    // MARK: Lifecycle

    init(options: OpenAPIExportOptions) {
        self.options = options
    }

    // MARK: Internal

    func build(from transactions: [HTTPTransaction]) -> OpenAPIDocumentBuildResult {
        var operations: [EndpointKey: OperationAccumulator] = [:]
        var orderedKeys: [EndpointKey] = []
        var servers: [String] = []
        var skipped = 0
        var exported = 0
        var hasBearerAuth = false

        for transaction in transactions {
            guard OpenAPITransactionFilter.isEligible(transaction),
                  let method = OpenAPIHTTPMethod(rawValue: transaction.request.method.lowercased()),
                  let origin = transaction.request.url.openapiOrigin else
            {
                skipped += 1
                continue
            }

            let inferredPath = OpenAPIPathTemplateInferer.infer(from: transaction.request.url)
            let key = EndpointKey(path: inferredPath.template, method: method)
            if operations[key] == nil {
                operations[key] = OperationAccumulator(
                    key: key,
                    pathParameters: inferredPath.parameters
                )
                orderedKeys.append(key)
            }
            operations[key]?.consume(transaction)
            if !servers.contains(origin) {
                servers.append(origin)
            }
            if OpenAPISecurityDetector.hasBearerAuthorization(transaction.request.headers) {
                hasBearerAuth = true
            }
            exported += 1
        }

        var paths: [String: Any] = [:]
        for key in orderedKeys.sorted() {
            guard let operation = operations[key] else {
                continue
            }
            var pathItem = paths[key.path] as? [String: Any] ?? [:]
            pathItem[key.method.rawValue] = operation.toDictionary()
            paths[key.path] = pathItem
        }

        var document: [String: Any] = [
            "openapi": "3.0.3",
            "info": [
                "title": options.title,
                "version": options.version,
                "description": "Generated by Rockxy from captured HTTP traffic. Schemas are inferred from observed requests and responses."
            ],
            "servers": servers.map { ["url": $0] },
            "paths": paths
        ]

        if hasBearerAuth {
            document["components"] = [
                "securitySchemes": [
                    "bearerAuth": [
                        "type": "http",
                        "scheme": "bearer"
                    ]
                ]
            ]
        }

        return OpenAPIDocumentBuildResult(
            document: document,
            exportedTransactionCount: exported,
            skippedTransactionCount: skipped
        )
    }

    // MARK: Private

    private let options: OpenAPIExportOptions
}

// MARK: - OpenAPITransactionFilter

private enum OpenAPITransactionFilter {
    static func isEligible(_ transaction: HTTPTransaction) -> Bool {
        let request = transaction.request
        guard let scheme = request.url.scheme?.lowercased(),
              ["http", "https"].contains(scheme),
              request.url.host() != nil,
              OpenAPIHTTPMethod(rawValue: request.method.lowercased()) != nil
        else {
            return false
        }
        if request.method.uppercased() == "CONNECT" {
            return false
        }
        if transaction.webSocketConnection != nil || transaction.response?.statusCode == 101 {
            return false
        }
        return true
    }
}

// MARK: - OpenAPIHTTPMethod

private enum OpenAPIHTTPMethod: String, Comparable {
    case delete
    case get
    case head
    case options
    case patch
    case post
    case put
    case trace

    static func < (lhs: OpenAPIHTTPMethod, rhs: OpenAPIHTTPMethod) -> Bool {
        lhs.sortIndex < rhs.sortIndex
    }

    private var sortIndex: Int {
        switch self {
        case .get: 0
        case .post: 1
        case .put: 2
        case .patch: 3
        case .delete: 4
        case .head: 5
        case .options: 6
        case .trace: 7
        }
    }
}

// MARK: - EndpointKey

private struct EndpointKey: Hashable, Comparable {
    let path: String
    let method: OpenAPIHTTPMethod

    static func < (lhs: EndpointKey, rhs: EndpointKey) -> Bool {
        if lhs.path == rhs.path {
            return lhs.method < rhs.method
        }
        return lhs.path < rhs.path
    }
}

// MARK: - OperationAccumulator

private struct OperationAccumulator {
    // MARK: Lifecycle

    init(key: EndpointKey, pathParameters: [OpenAPIParameter]) {
        self.key = key
        self.pathParameters = pathParameters
    }

    // MARK: Internal

    let key: EndpointKey
    let pathParameters: [OpenAPIParameter]
    var querySamples: [String: [String]] = [:]
    var requestBodySamples: [String: [Any]] = [:]
    var requestBodyBinaryMediaTypes: Set<String> = []
    var responses: [String: ResponseAccumulator] = [:]
    var responseOrder: [String] = []
    var hasBearerAuth = false

    mutating func consume(_ transaction: HTTPTransaction) {
        consumeQuery(from: transaction.request.url)
        consumeRequestBody(transaction.request)
        consumeResponse(transaction.response)
        if OpenAPISecurityDetector.hasBearerAuthorization(transaction.request.headers) {
            hasBearerAuth = true
        }
    }

    func toDictionary() -> [String: Any] {
        var operation: [String: Any] = [
            "operationId": operationID,
            "tags": [tag],
            "responses": responseDictionary()
        ]

        let parameters = parameterDictionaries()
        if !parameters.isEmpty {
            operation["parameters"] = parameters
        }
        if !requestBodySamples.isEmpty || !requestBodyBinaryMediaTypes.isEmpty {
            operation["requestBody"] = requestBodyDictionary()
        }
        if hasBearerAuth {
            operation["security"] = [["bearerAuth": []]]
        }
        return operation
    }

    // MARK: Private

    private var operationID: String {
        let raw = "\(key.method.rawValue)_\(key.path)"
        let scalars = raw.unicodeScalars.map { scalar -> Character in
            CharacterSet.alphanumerics.contains(scalar) ? Character(scalar) : "_"
        }
        return String(scalars)
            .split(separator: "_")
            .filter { !$0.isEmpty }
            .joined(separator: "_")
    }

    private var tag: String {
        key.path
            .split(separator: "/")
            .first
            .map(String.init) ?? "default"
    }

    private mutating func consumeQuery(from url: URL) {
        let queryItems = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems ?? []
        for item in queryItems where !MCPRedactionPolicy.sensitiveQueryParams.contains(item.name.lowercased()) {
            querySamples[item.name, default: []].append(item.value ?? "")
        }
    }

    private mutating func consumeRequestBody(_ request: HTTPRequestData) {
        guard let body = request.body, !body.isEmpty else {
            return
        }
        let mediaType = OpenAPIMediaTypeResolver.mediaType(headers: request.headers, contentType: request.contentType)
        switch request.contentType {
        case .some(.json):
            if let object = OpenAPIBodySanitizer.jsonObject(from: body) {
                requestBodySamples[mediaType, default: []].append(object)
            }
        case .some(.form):
            let formObject = OpenAPIBodySanitizer.formObject(from: body)
            if !formObject.isEmpty {
                requestBodySamples[mediaType, default: []].append(formObject)
            }
        case .some(.text), .some(.html), .some(.xml):
            requestBodySamples[mediaType, default: []].append("")
        default:
            requestBodyBinaryMediaTypes.insert(mediaType)
        }
    }

    private mutating func consumeResponse(_ response: HTTPResponseData?) {
        guard let response else {
            if responses["default"] == nil {
                responses["default"] = ResponseAccumulator(statusCode: "default", description: "No response captured")
                responseOrder.append("default")
            }
            return
        }

        let statusCode = "\(response.statusCode)"
        if responses[statusCode] == nil {
            responses[statusCode] = ResponseAccumulator(
                statusCode: statusCode,
                description: response.statusMessage.isEmpty ? "HTTP \(statusCode)" : response.statusMessage
            )
            responseOrder.append(statusCode)
        }
        responses[statusCode]?.consume(response)
    }

    private func parameterDictionaries() -> [[String: Any]] {
        var parameters = pathParameters.map { $0.toDictionary() }
        for name in querySamples.keys.sorted() {
            guard let values = querySamples[name] else {
                continue
            }
            let schema: [String: Any]
            var parameter: [String: Any] = [
                "name": name,
                "in": "query",
                "required": false
            ]
            if values.count > 1 {
                schema = [
                    "type": "array",
                    "items": OpenAPISchemaInferer.schema(forScalars: values)
                ]
                parameter["style"] = "form"
                parameter["explode"] = true
            } else {
                schema = OpenAPISchemaInferer.schema(forScalars: values)
            }
            parameter["schema"] = schema
            parameters.append(parameter)
        }
        return parameters
    }

    private func requestBodyDictionary() -> [String: Any] {
        var content: [String: Any] = [:]
        for mediaType in requestBodySamples.keys.sorted() {
            let samples = requestBodySamples[mediaType] ?? []
            content[mediaType] = ["schema": OpenAPISchemaInferer.schema(forJSONSamples: samples)]
        }
        for mediaType in requestBodyBinaryMediaTypes.sorted() {
            content[mediaType] = ["schema": OpenAPISchemaInferer.binarySchema]
        }
        return [
            "required": true,
            "content": content
        ]
    }

    private func responseDictionary() -> [String: Any] {
        var result: [String: Any] = [:]
        let keys = responseOrder.sorted { lhs, rhs in
            if lhs == "default" {
                return false
            }
            if rhs == "default" {
                return true
            }
            return (Int(lhs) ?? .max) < (Int(rhs) ?? .max)
        }
        for key in keys {
            result[key] = responses[key]?.toDictionary() ?? ["description": "HTTP \(key)"]
        }
        if result.isEmpty {
            result["default"] = ["description": "No response captured"]
        }
        return result
    }
}

// MARK: - ResponseAccumulator

private struct ResponseAccumulator {
    let statusCode: String
    var description: String
    var bodySamples: [String: [Any]] = [:]
    var binaryMediaTypes: Set<String> = []
    var hasContent = false

    mutating func consume(_ response: HTTPResponseData) {
        guard let body = response.body, !body.isEmpty else {
            return
        }
        hasContent = true
        if response.bodyTruncated {
            return
        }
        let mediaType = OpenAPIMediaTypeResolver.mediaType(headers: response.headers, contentType: response.contentType)
        switch response.contentType {
        case .some(.json):
            if let object = OpenAPIBodySanitizer.jsonObject(from: body) {
                bodySamples[mediaType, default: []].append(object)
            }
        case .some(.text), .some(.html), .some(.xml):
            bodySamples[mediaType, default: []].append("")
        default:
            binaryMediaTypes.insert(mediaType)
        }
    }

    func toDictionary() -> [String: Any] {
        var response: [String: Any] = ["description": description]
        var content: [String: Any] = [:]
        for mediaType in bodySamples.keys.sorted() {
            let samples = bodySamples[mediaType] ?? []
            content[mediaType] = ["schema": OpenAPISchemaInferer.schema(forJSONSamples: samples)]
        }
        for mediaType in binaryMediaTypes.sorted() {
            content[mediaType] = ["schema": OpenAPISchemaInferer.binarySchema]
        }
        if !content.isEmpty {
            response["content"] = content
        }
        return response
    }
}

// MARK: - OpenAPISecurityDetector

private enum OpenAPISecurityDetector {
    static func hasBearerAuthorization(_ headers: [HTTPHeader]) -> Bool {
        headers.contains { header in
            header.name.localizedCaseInsensitiveCompare("Authorization") == .orderedSame
                && header.value.range(of: #"^\s*Bearer\s+\S+"#, options: [.regularExpression, .caseInsensitive]) != nil
        }
    }
}

// MARK: - OpenAPIMediaTypeResolver

private enum OpenAPIMediaTypeResolver {
    static func mediaType(headers: [HTTPHeader], contentType: ContentType?) -> String {
        if let raw = headers.first(where: { $0.name.localizedCaseInsensitiveCompare("Content-Type") == .orderedSame })?.value {
            let mediaType = raw
                .split(separator: ";", maxSplits: 1)
                .first?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if let mediaType, !mediaType.isEmpty {
                return mediaType.lowercased()
            }
        }
        switch contentType {
        case .some(.json): return "application/json"
        case .some(.form): return "application/x-www-form-urlencoded"
        case .some(.multipartForm): return "multipart/form-data"
        case .some(.xml): return "application/xml"
        case .some(.html): return "text/html"
        case .some(.text): return "text/plain"
        case .some(.protobuf): return "application/protobuf"
        case .some(.image), .some(.binary), .some(.unknown), nil: return "application/octet-stream"
        }
    }
}

// MARK: - OpenAPIBodySanitizer

private enum OpenAPIBodySanitizer {
    static func jsonObject(from data: Data) -> Any? {
        guard let object = try? JSONSerialization.jsonObject(with: data) else {
            return nil
        }
        return sanitizeJSON(object)
    }

    static func formObject(from data: Data) -> [String: Any] {
        guard let text = String(data: data, encoding: .utf8) else {
            return [:]
        }
        var result: [String: Any] = [:]
        for pair in text.split(separator: "&") {
            let parts = pair.split(separator: "=", maxSplits: 1)
            guard let keyPart = parts.first else {
                continue
            }
            let key = String(keyPart).removingPercentEncoding ?? String(keyPart)
            guard !MCPRedactionPolicy.sensitiveBodyKeys.contains(key.lowercased()),
                  !MCPRedactionPolicy.sensitiveQueryParams.contains(key.lowercased()) else {
                continue
            }
            let value = parts.dropFirst().first.map(String.init)?.removingPercentEncoding ?? ""
            result[key] = value
        }
        return result
    }

    private static func sanitizeJSON(_ object: Any) -> Any {
        if let dictionary = object as? [String: Any] {
            var result: [String: Any] = [:]
            for key in dictionary.keys.sorted()
                where !MCPRedactionPolicy.sensitiveBodyKeys.contains(key.lowercased())
                    && !MCPRedactionPolicy.sensitiveQueryParams.contains(key.lowercased())
            {
                result[key] = sanitizeJSON(dictionary[key] as Any)
            }
            return result
        }
        if let array = object as? [Any] {
            return array.map { sanitizeJSON($0) }
        }
        return object
    }
}

// MARK: - URL + OpenAPI

private extension URL {
    var openapiOrigin: String? {
        guard let scheme, let host = host() else {
            return nil
        }
        var origin = "\(scheme)://\(host)"
        if let port {
            origin += ":\(port)"
        }
        return origin
    }
}
